// pub mod convertFullwidthCharsToASCII;
// pub mod getChunk;
// pub mod getChunkSize;
// pub mod hiraganaToKatakana;
// pub mod isCharConsonant;
// pub mod isCharEnglishPunctuation;
// pub mod isCharHiragana;
pub mod isCharInRange;
// pub mod isCharJapanesePunctuation;
// pub mod isCharJapanese;
// pub mod isCharKana;
pub mod isCharKanji;
// pub mod isCharKatakana;
// pub mod isCharLongDash;
// pub mod isCharPunctuation;
// pub mod isCharRomaji;
// pub mod isCharSlashDot;
// pub mod isCharUpperCase;
// pub mod isCharVowel;
// pub mod katakanaToHiragana;
// pub mod logInputEvents;
// pub mod romajiToHiragana;